layout={
  main={
    LinearLayout,
    layout_width="fill",
    layout_height="fill",
    orientation="vertical";

    {
      HorizontalScrollView;
      id="工具栏",
      layout_width="-1";
      horizontalScrollBarEnabled=false;
      {
        LinearLayout;
        orientation="horizontal";
        layout_height="-2";
        -- gravity="center";
        layout_width="-1";
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="打开";
            textSize="20sp";
            Text="打开",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="最近";
            textSize="20sp";
            Text="最近",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="工程";
            textSize="20sp";
            Text="工程",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="打包";
            textSize="20sp";
            Text="打包",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="新建工程";
            textSize="20sp";
            Text="新建工程",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="导出";
            textSize="20sp";
            Text="导出",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="属性";
            textSize="20sp";
            Text="属性",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="保存";
            textSize="20sp";
            Text="保存",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="新建";
            textSize="20sp";
            Text="新建",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="编译";
            textSize="20sp";
            Text="编译",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="查错";
            textSize="20sp";
            Text="查错",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="搜索";
            textSize="20sp";
            Text="搜索",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="转到";
            textSize="20sp";
            Text="转到",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="导航";
            textSize="20sp";
            Text="导航",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };

        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="格式化";
            textSize="20sp";
            Text="格式化",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };

        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="分析";
            textSize="20sp";
            Text="分析",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };

        {
          LinearLayout;
          orientation="horizontal";
          layout_height="-2";
          gravity="center";
          layout_width="wrap";
          {
            TextView;
            layout_marginLeft="20dp";
            TextColor="0xff000000";
            id="日志";
            textSize="20sp";
            Text="日志",
            Gravity="center";
            layout_height="wrap";
            layout_width="wrap";
          };
        };
      };
    } ;

    {
      HorizontalScrollView;
      --   layout_marginTop="3dp";
      layout_width="-1";
      layout_height="wrap";
      horizontalScrollBarEnabled=false;
      {
        LinearLayout;
        orientation="horizontal";
        layout_height="-2";
        gravity="center";
        layout_width="wrap";
        id="spq2",
      };
    };
  
    {
      FrameLayout;
      layout_height="wrap";
      -- layout_marginTop="80dp";
      layout_width="-1";
      {
        HorizontalListView;
        --    layout_marginTop="3dp";
        id="spq2";
        layout_height="wrap";
        horizontalScrollBarEnabled=false;
      };
    };


    {
      LuaEditor,
      id="editor",
      text="",
      layout_width="fill",
      layout_height="fill",
      layout_weight=1 ,
      --gravity="top"
    },
    {
      HorizontalScrollView;
      horizontalScrollBarEnabled=false,
      {
        LinearLayout;
        id="ps_bar";
        layout_width="fill";
      };
      layout_width="fill";
    };
  },

  build={
    ScrollView ,
    layout_width="fill",
    {
      LinearLayout,
      orientation=1,
      layout_width="fill",
      paddingLeft=20,
      {
        TextView,
        text="脚本路径"
      },
      {
        EditText,
        id="luaPath",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="包名称"
      },
      {
        EditText,
        id="packageName",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="程序名称"
      },
      {
        EditText,
        id="appName",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="程序版本"
      },
      {
        EditText,
        id="appVer",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="apk路径"
      },
      {
        EditText,
        id="apkPath",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="打包使用debug签名",
        id="status"
      },
    }
  },

  project={
    ScrollView ,
    layout_width="fill",
    {
      LinearLayout,
      orientation=1,
      layout_width="fill",
      padding="10dp",
      {
        TextView,
        text="程序名称"
      },
      {
        EditText,
        id="project_appName",
        text="demo",
        layout_width="fill",
        singleLine=true,
      },
      {
        TextView,
        text="包名称"
      },
      {
        EditText,
        id="project_packageName",
        text="com.Blua.demo",
        layout_width="fill",
        singleLine=true,
      },
    }
  },
  open2={
    LinearLayout;
    orientation="vertical";
    {
      EditText;
      layout_width="fill";
      id="open_edit";
    };
    {
      ListView;
      layout_width="fill";
      id="listview2";
    };
  };


}
