appname="小工具"
appver="1"
appcode="1"
appsdk="15"
path_pattern=""
packagename="com.biao.smallbox"
theme="Theme_DeviceDefault_Light_NoActionBar"
app_key="4yCilmN24RCRG82uc93kSZ1F"
app_channel=""
developer=""
description=""
debugmode=true
user_permission={
  "ACCESS_MEDIA_LOCATION",
  "ACCESS_NETWORK_STATE",
  "ACCESS_WIFI_STATE",
  "BATTERY_STATS",
  "CLEAR_APP_CACHE",
  "FOREGROUND_SERVICE",
  "GET_PACKAGE_SIZE",
  "INTERNET",
  "KILL_BACKGROUND_PROCESSES",
  "READ_EXTERNAL_STORAGE",
  "READ_FRAME_BUFFER",
  "READ_LOGS",
  "READ_PHONE_STATE",
  "REQUEST_INSTALL_PACKAGES",
  "SYSTEM_ALERT_WINDOW",
  "VIBRATE",
  "WRITE_EXTERNAL_STORAGE",
  "WRITE_SMS"
}
