appname="悬浮窗浏览器"
appver="1.0"
packagename="com.biao.xfcllq"
theme="Theme_Material_NoActionBar"--黑色MD
--theme="Theme_DeviceDefault_Light_NoActionBar"--白色
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE",
}
